# Goodbye messages module

# Goodbye phrases; yeah I know they're cheesy, but I'm a dog person.
declare -a goodbye_text=(
    "Woof woof! (Goodbye!)"
    "Tail wags for now!"
    "Catch you at the park!"
    "See you later, pup!"
    "Bone-voyage!"
    "Stay paw-sitive!"
    "Paws out!"
    "Fur-well!"
    "Un-leash the fun until next time!"
    "Stop, drop, and roll over!"
    "Hope your day is paw-some!"
    "Bark at you later!"
    "Have a howling good time!"
    "Don't work too hard, stay ruff!"
    "Keep your tail held high!"
    "Stay furry, my friend!"
    "A round of a-paws for your work today!"
    "Fur-ever yours!"
    "Sniff you soon!"
    "Be the good boy I know you are!"
    "Time to go for a walkies!"
    "Back to the kennel!"
    "Rest your paws!"
    "Stay fetching!"
    "Don't stop re-triever-ing!"
    "Paws and reflect on a job well done!"
    "You're the leader of the pack!"
    "Wag more, bark less!"
    "Life is ruff, but you're doing great!"
    "Everything is paw-sible!"
    "You're a real treat!"
    "No more digging for today!"
    "Go fetch some rest!"
    "Stay paws-ed until we meet again!"
    "A-woooooo! (See ya!)"
    "Keep on wagging!"
    "Hope your dreams are full of squirrels!"
    "Keep your nose to the ground!"
    "Stay loyal to the yard!"
    "You've earned a gold medal in fetching!"
    "Quit hounding me and go play!"
    "See you in the dog days!"
    "You're the top dog!"
    "Don't let the cat get your tongue!"
    "Pawsitively finished for now!"
    "Time to curl up and nap!"
    "Lick you later!"
    "Sniff out some fun!"
    "Keep your ears up!"
    "Stay paw-some!"
    "Woofing you all the best!"
    "Catch you on the flip-flop (or the flip-paw)!"
    "Happy trails and wagging tails!"
    "Don't bark up the wrong tree!"
    "You're a fur-midable human!"
    "Stay dogged in your pursuits!"
    "A wagging tail is a happy heart!"
    "Chew on that until next time!"
    "Paws for thought!"
)